### PR TITLE
stylesheets, users dashboard, post helper and views modified

### PR DESCRIPTION
**Pull request by maximho**

### CODE REVIEW

**Comment by gustavoguimaraes** [comment]
Hey Max,

So this fixes the problem, right?

**Comment by maximho** [comment]
Hey Gustavo! this helps to be close. This puts the logos in a same size and the titles at the same height, but still there is the problem of the description. Duilio says a table format could works as we thought it. Anyway there is some changes in post helpers that has to do with functionality of the app in general. I would merge it.

**Comment by gustavoguimaraes** [comment]
sounds good :+1:

**Comment by maximho** [comment]
;)

**Pull request merged**
